CREATE DATABASE AssignmentATJB;
CREATE TABLE May(
    MaMay CHAR(5) PRIMARY KEY,
    ViTri NVARCHAR(50),
    TrangThai NVARCHAR(50)
);

CREATE TABLE KhachHang(
    MaKH CHAR(5) PRIMARY KEY,
    TenKH NVARCHAR(50),
    DiaChi NVARCHAR(50),
    SDT CHAR(12),
    Email NVARCHAR(50)
)

CREATE TABLE DichVu(
 MaDV CHAR(5) PRIMARY KEY,
 TenDV NVARCHAR(50),
 DonViTinh NVARCHAR(30),
 DonGia INT
);

CREATE TABLE SuDungDV(
    MaKH CHAR(5),
    MaDV CHAR(5),
    NgaySD VARCHAR(20),
    GioSD VARCHAR(20),
    SoLuong INT
    CONSTRAINT Pk PRIMARY KEY(MaKH, MaDV, NgaySD, GioSD),
    CONSTRAINT Fk_KH FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT FK_DV FOREIGN KEY(MaDV) REFERENCES DichVu(MaDV)
)

CREATE TABLE SuDungMay(
    MaKH CHAR(5),
    MaMay CHAR(5),
    NgayBD NVARCHAR(20),
    GioBD NVARCHAR(20),
    ThoiGianSD INT,
    CONSTRAINT PkSDM PRIMARY KEY(MaKH, MaMay, NgayBD, GioBD),
    CONSTRAINT Fk_KHSDM FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT Fk_M FOREIGN KEY(MaMay) REFERENCES May(MaMay)
)